#!/usr/bin/env node
/* Write tools/phrases/<game>.txt straight out of a game's TEXT-CORE block.
 *
 *   node tools/gen-phrases.js <game-folder> [--voice en-GB-SoniaNeural]
 *
 * Generic version of the per-game gen-phrases-*.js: the game keeps every line it
 * can say in one block marked TEXT-CORE (no DOM inside) with a phraseList()
 * that returns the already split segments. Used by the homework generator
 * (second-brain/scripts/jack_homework.py) for the games it builds.
 * Exits 1 when the markers or phraseList() are missing, so the caller knows.
 */
'use strict';
var fs = require('fs');
var path = require('path');

var args = process.argv.slice(2);
var game = args[0];
var vi = args.indexOf('--voice');
var voice = vi >= 0 ? args[vi + 1] : 'en-GB-SoniaNeural';
if (!game) { console.error('usage: gen-phrases.js <game-folder> [--voice <voice>]'); process.exit(1); }

var ROOT = path.dirname(__dirname);
var file = path.join(ROOT, game, 'index.html');
var out = path.join(ROOT, 'tools', 'phrases', game + '.txt');
try {
  var src = fs.readFileSync(file, 'utf8');
  var start = src.indexOf('/* ==== TEXT-CORE ====');
  var end = src.indexOf('/* ==== END TEXT-CORE ==== */');
  if (start < 0 || end < 0) throw new Error('TEXT-CORE markers not found in ' + file);
  var phrases = new Function(src.slice(start, end) + '\nreturn phraseList();')();
  if (!Array.isArray(phrases) || !phrases.length) throw new Error('phraseList() returned nothing');
  var seen = {}, list = [];
  phrases.forEach(function (p) {
    p = String(p).replace(/\s+/g, ' ').trim();
    if (p && !seen[p]) { seen[p] = 1; list.push(p); }
  });
  var header = ['# voice: ' + voice,
    '# ' + game + ' — every line the game speaks, already split into segments.',
    '# GENERATED by tools/gen-phrases.js from the TEXT-CORE block in ' + game + '/index.html.',
    '# Edit the game, not this file.', ''];
  fs.writeFileSync(out, header.concat(list).join('\n') + '\n', 'utf8');
  console.log(list.length + ' phrases -> ' + path.relative(ROOT, out));
} catch (e) {
  console.error('gen-phrases: ' + e.message);
  process.exit(1);
}
